import gql from 'graphql-tag'

export const SINGLE_EVENT_QUERY = gql `
    query allEvents($id: ID) {
        allEvents(filter: {id: $id}){
            id
            courseName
            academicYear
            students{
                id
                name
                email
            }
            jurys{
                id
                name
                company
                email
            }
            projects{
                id
                name
                description
            }
            meetings{
                id
                author{
                    name
                }
                student{
                    name
                }
            }
        }
    }
`;