import gql from 'graphql-tag'

export const TABLE_EVENT_SUBSCRIPTION = gql `
subscription Score($id: ID!){
    Score(
        filter: {
        mutation_in: [CREATED],
        node: {
            event_some: {id: $id}
        }
    }
    ) {
        node{
            score
            event{
                id
            }
            implementation{
                id
            }
            comment
            id
            meeting{
                author{
                    name
                }
                student{
                    name
                    id
                }
            }
        }
    }
}
`