import gql from 'graphql-tag'

export const TABLE_EVENT_SUBSCRIPTION = gql `
subscription Score($id: ID!){
    Score(
        filter: {
        mutation_in: [CREATED]
        node: {
            meeting:{
            event: {
                id: $id
                students_every: {
                studentEvents_some: {
                    id: $id
                }
                }
            }
            }
        }
        }
    ) {
    node{
        meeting{
            event {
            id
                courseName
                    students{
                name
                implementations {
                    project{
                        name
                    }
                    scores {
                        score
                        comment
                        meeting{
                            author{
                                name
                            }
                        }
                    }
                }
            }
            }
        }
        }
    }
    }
`