import gql from 'graphql-tag'

export const TABLE_EVENT_QUERY = gql `
query Event($id: ID!){
    Event(id : $id){
        courseName
        students{
            name
            implementations(filter: {events_every: {id: $id}}) {
                id
                project{
                    name
                }
                scores {
                    id
                    score
                    comment
                    meeting{
                        author{
                            name
                        }
                    }
                }
            }
        }
    }
}
`