import gql from 'graphql-tag'

export const ALL_EVENT_QUERY = gql `
    query allEvents {
        allEvents(filter: {
            softDelete: false
        }){
            id
            courseName
            academicYear
            jurys{
                id
            }
            students{
                id
            }
        }
    }
`;