import gql from 'graphql-tag'

export const CREATE_IMPLEMENTATIONS_MUTATION = gql `
    mutation CreateImplementation($softDelete: Boolean!, $eventId: ID!, $projectId: ID!, $studentId: ID!, $weight: Float!) {
        createImplementation(softDelete: $softDelete, eventId: $eventId, projectId: $projectId, studentId: $studentId, weight: $weight) {
            id
        }
    }
`;