import gql from 'graphql-tag'

export const UPDATE_IMPLEMENTATION_MUTATION = gql `
    mutation updateImplementation($id: ID!, $weight: Float!) {
        updateImplementation(id: $id, weight: $weight) {
            id
            weight
        }
    }
`;