import gql from 'graphql-tag'

export const CREATE_IMPLEMENTATIONS_MUTATION = gql `
    mutation CreateImplementation($softDelete: Boolean!, $eventsIds: [ID!]!, $projectId: ID!, $studentId: ID!, $weight: Float!) {
        createImplementation(softDelete: $softDelete, eventsIds: $eventsIds, projectId: $projectId, studentId: $studentId, weight: $weight) {
            id
        }
    }
`;