import gql from 'graphql-tag'

export const CREATE_IMPLEMENTATIONS_MUTATION = gql `
    mutation CreateImplementation($softDelete: Boolean!, $eventId: ID!, $projectId: ID!, $studentsIds: [ID!]!, $weight: Float!) {
        createImplementation(softDelete: $softDelete, eventId: $eventId, projectId: $projectId, studentsIds: $studentsIds, weight: $weight) {
            id
        }
    }
`;