import gql from 'graphql-tag'

export const SINGLE_MEETING_QUERY = gql `
    query allMeetings($id: ID, $eventId: ID) {
        allMeetings(filter: {id: $id}){
            id
            student{
                name
                id
                implementations(filter: {event: {id: $eventId}}) {
                    id
                    project{
                        name
                    }
                }
            }
        }
    }
`;