import gql from 'graphql-tag'

export const SINGLE_MEETING_DATA_QUERY = gql `
    query allMeetings($id: ID, $studentId: ID) {
        allMeetings(filter: {id: $id}){
            id
            student{
                name
                id
            }
            event{
                id
                implementations(filter: {students_every: {id: $studentId} }){
                    id
                    project{
                        name
                        description
                    }
                }
            }
        }
    }
`;