import gql from 'graphql-tag'

export const CREATE_STUDENT_MUTATION = gql `
    mutation CreateProject($description: String!, $name: String!, $softDelete: Boolean!) {
        createProject(name: $name, description: $description, softDelete: $softDelete) {
            name
            description
        }
    }
`;