import gql from 'graphql-tag'

export const SCORE_SUBSCRIPTION = gql`
    subscription Score{
      Score(filter: {
        mutation_in: [CREATED]
      }) {
        node {
          id
          text
          createdAt
          sentBy {
            id
            name
          }
        }
      }
    }
  `;