import gql from 'graphql-tag'

export const CREATE_SCORE_MUTATION = gql `
    mutation CreateScore($meetingId: ID!, $implementationId: ID!, $comment: String, $score: Float!, $softDelete: Boolean!, $eventIds: [ID!]!) {
        createScore(meetingId: $meetingId, eventIds: $eventIds, implementationId: $implementationId, comment: $comment, score: $score,softDelete: $softDelete) {
            id
        }
    }
`;