import gql from 'graphql-tag'

export const CREATE_STUDENT_MUTATION = gql`
  mutation createStudent($id: String!, $name: String!, $email: String!) {
    createStudent(
        id: $id,
        name: $name,
        email: $email,
        ) {
        name
        email
    }
  }
`;