import gql from 'graphql-tag'

export const DESACTIVATE_STUDENT_MUTATION = gql `
    mutation UpdateStudent($id: ID!, $softDelete: Boolean!){
        updateStudent(id: $id, softDelete: $softDelete){
            id
        }
    }
`;