import gql from 'graphql-tag'

export const ALL_STUDENT_QUERY = gql `
    query allStudents {
        allStudents{
            id
            name
            email
            implementations{
                id
                project{
                    name
                    description
                }
            }
            studentEvents{
                id
            }
        }
    }
`;