import gql from 'graphql-tag'

export const CREATE_STUDENT_MUTATION = gql `
    mutation CreatStudent($email: String!, $name: String!, $softDelete: Boolean!) {
        createStudent(name: $name, email: $email, softDelete: $softDelete) {
            name
            email
        }
    }
`;