import gql from 'graphql-tag'

export const ALL_STUDENT_QUERY = gql `
    query allStudents {
        allStudents(filter: {
            softDelete: false
        }){
            id
            name
            email
            implementations{
                id
                project{
                    id
                    name
                    description
                }
            }
            studentEvents{
                id
            }
        }
    }
`;