import gql from 'graphql-tag'

export const STUDENT_QUERY = gql`
    query Student($id: ID!) {
        Student(id: $id) {
            id
            email
            name
            studentEvents{
                id
                courseName
                academicYear
            }
            implementations{
                id
                weight
                event{
                    courseName
                    academicYear
                }
                project{
                    name
                    description
                    weight
                }
            }
        }
    }
`;