import gql from 'graphql-tag'

export const ALL_USER_QUERY = gql `
    query allUsers {
        allUsers{
            id
            name
            company
            email
            juryEvents{
                id
            }
            meetings{
                id
            }
        }
    }
`;