import gql from 'graphql-tag'

export const USER_QUERY = gql`
    query User($id: ID!) {
        User(id: $id) {
            id
            email
            name
            company
            isAdmin
            juryEvents{
                id
            }
            meetings{
                id
            }
        }
    }
`;