import gql from 'graphql-tag'

export const ALL_USER_QUERY = gql `
    query allUsers {
        allUsers(filter: {
            softDelete: false
        }){
            id
            name
            company
            email
            softDelete
            juryEvents{
                id
            }
            meetings{
                id
            }
        }
    }
`;