import gql from 'graphql-tag'

export const DESACTIVATE_USER_MUTATION = gql `
    mutation UpdateUser($id: ID!, $softDelete: Boolean!){
        updateUser(id: $id, softDelete: $softDelete){
            id
        }
    }
`;