import gql from 'graphql-tag'

export const USER_QUERY = gql`
    query User($id: ID!) {
        User(id: $id) {
            id
            email
            name
            company
            isAdmin
            juryEvents{
                id
                courseName
                academicYear
            }
            meetings{
                id
                evaluation
                comment
                event{
                    courseName
                    academicYear
                }
                student{
                    name
                }
            }
        }
    }
`;